# Default values for dogecoin.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

statefulset:
  # podManagementPolicy could be:
  # Parallel or OrderedReady
  podManagementPolicy: Parallel
  updateStrategy:
    # The spec.updateStrategy.type field accepts either 
    # OnDelete or RollingUpdate as values
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  volumeClaimTemplates:
    storageClassName: ""
    storage: 500Gi

rpcuser: rpcuser
rpcpassword: rpcpass
blocknotify:

image:
  repository: kylemanna/dogecoind 
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

environment: []

terminationGracePeriodSeconds: 60

#livenessProbe:
#  httpGet:
#    path: /
#    port: http

#readinessProbe:
#  httpGet:
#    path: /
#    port: http


serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

service:
  type: ClusterIP
  services:
  - name: rpc
    targetPort: 8332
    port: 8332
    protocol: TCP
    # nodePort: 30032
  - name: p2p
    targetPort: 8333
    port: 8333
    protocol: TCP
    # nodePort: 30033
  
resources:
  limits: {}
    # cpu: 1500m
    # memory: 3072Mi
  requests: {}
    # cpu: 1500m
    # memory: 3072Mi

nodeSelector: {}

tolerations: []

affinity: {}

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: dogecoin-0.dom.ltd
      paths: ["/"]
      servicePort: "8332"
  tls:
    - secretName: dogecoin-0-dom-ltd
      hosts:
        - dogecoin-0.dom.ltd
