apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dogecoin.fullname" . }}
  labels:
    {{- include "dogecoin.labels" . | nindent 4 }}
data:
  dogecoin.conf: |-
    server=1
    printtoconsole=1
    rpcuser={{ .Values.rpcuser }}
    rpcpassword={{ .Values.rpcpassword }}
    rpcallowip=0.0.0.0/0    
    {{- if .Values.blocknotify }}
    blocknotify={{ .Values.blocknotify }}   
    {{- end }}
    rpcthreads=16
    rpcworkqueue=64
    keypool=1
