apiVersion: v1
kind: Service
metadata:
  name: {{ include "dogecoin.fullname" . }}
  labels:
    {{- include "dogecoin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
{{- range .Values.service.services }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
      name: {{ .name }}
{{- if and (eq $.Values.service.type "NodePort") ( .nodePort ) }}
      nodePort: {{ .nodePort }}
{{- end }}
{{- end }}
  selector:
    {{- include "dogecoin.selectorLabels" . | nindent 4 }}
